name: build-sign-verify-node

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  lint-source:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
    - name: Setup node
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3
      with:
        node-version: 16
        cache: npm
    - name: Install dependencies
      run: npm install
    - name: Run linter
      run: npm run lint:check

  run-tests:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.13.0
          - 12.x
          - 14.15.0
          - 14.x
          - 16.0.0
          - 16.x
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: cmd
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
    - name: Checkout source
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
    - name: Setup node
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test:ci

  build-package:
    name: Build Package
    needs: [lint-source, run-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout source
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
    - name: Setup node
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3
      with:
        node-version: 16
        cache: npm
    - name: Install dependencies
      run: npm install
    - name: Create package
      run: |
        npm run build
        npm pack
    - name: Sign package
      run: |
        ./bin/sigstore.js sign sigstore-0.0.0.tgz > artifact.sig
    - name: Archive package
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3
      with:
        name: package
        path: sigstore-0.0.0.tgz
    - name: Archive signature
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3
      with:
        name: signature
        path: artifact.sig
    - name: Archive certificate
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3
      with:
        name: certificate
        path: signingcert.pem

  verify-signature:
    name: Verify Signature
    needs: build-package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
    - name: Setup node
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3
      with:
        node-version: 16
        cache: npm
    - name: Install dependencies
      run: npm install
    - name: Download package
      uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3
      with:
        name: package
    - name: Download signature
      uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3
      with:
        name: signature
    - name: Download certificate
      uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3
      with:
        name: certificate
    - name: Compile sigstore
      run: |
        npm run build
    - name: Verify artifact signature
      run: |
        ./bin/sigstore.js verify sigstore-0.0.0.tgz artifact.sig signingcert.pem
